- platform: mqtt
  name: 'Tap Water'
  state_topic: 'home/ems-esp/tapwater_active'
  payload_on: "1"
  payload_off: "0"

- platform: mqtt
  name: 'Heating'
  state_topic: 'home/ems-esp/heating_active'
  payload_on: "1"
  payload_off: "0"