- id: '1543262156968'
  alias: Verzend mindergas.nl
  trigger:
  - at: '23:58:00'
    platform: time
  condition: []
  action:
  - service: rest_command.send_mindergas
- id: '1550605256142'
  alias: Update Yesterdays
  trigger:
  - hours: '23'
    minutes: '59'
    platform: time_pattern
    seconds: '30'
  condition: []
  action:
  - data:
      entity_id: sensor.yesterday_energy_consumption, sensor.yesterday_energy_netto,sensor.yesterday_energy_production,
        sensor.yesterday_growatt, sensor.daily_gas
    service: homeassistant.update_entity
- id: '1572807017314'
  alias: Nieuwe automatisering
  description: ''
  trigger:
  - at: 00:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: timer.werktijd
    service: timer.cancel
- id: '1572807441074'
  alias: Start werktimer
  description: ''
  trigger:
  - payload: '1'
    platform: mqtt
    topic: Wifi werk
  condition: []
  action:
  - data:
      entity_id: timer.werktijd
    service: timer.start
- id: '1572807512954'
  alias: Pauze werktijd
  description: ''
  trigger:
  - payload: '0'
    platform: mqtt
    topic: Wifi werk
  condition: []
  action:
  - data:
      entity_id: timer.werktijd
    service: timer.pause
- id: '1572807861692'
  alias: Werktijd klaar
  description: ''
  trigger:
  - event_data: {}
    event_type: timer.finished
    platform: event
  condition: []
  action:
  - data:
      payload: 1
      qos: 2
      topic: werktijd_klaar
    service: mqtt.publish
  - data:
      message: Tijd om naar huis te gaan.
    service: notify.pushbullet
- id: '1586287819028'
  alias: House consumption  when there is no sun
  description: ''
  trigger:
  - minutes: /1
    platform: time_pattern
  condition:
  - condition: state
    entity_id: sensor.growatt_total_maximum_power
    state: '0'
  action:
  - data: {}
    entity_id: sensor.usage_by_house_total
    service: homeassistant.update_entity
- id: '1586288695566'
  alias: Poll when there is not solar updates
  description: ''
  trigger:
  - minutes: /15
    platform: time_pattern
  condition: []
  action:
  - data: {}
    entity_id: sensor.usage_by_house_total
    service: homeassistant.update_entity
- id: '1602701838167'
  alias: Start babymonitor if stream is started
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.data_in_stream
  condition:
  - condition: numeric_state
    entity_id: sensor.data_in_stream
    above: '0'
  action:
  - service: ffmpeg.start
    data: {}
    entity_id: binary_sensor.ffmpeg_noise
  mode: single
