- action:
  - data:
      entity_id: media_player.kodi
      message: Hurry, your late!
    service: tts.google_say
  alias: Hurry your late
  condition:
  - after: '8:00'
    before: '9:00'
    condition: time
  id: automation_test
  trigger:
  - entity_id: device_tracker.nard
    event: enter
    platform: zone
    zone: zone.home
- action:
  - alias: ''
    data:
      entity_id: automation.hurry_your_late
    service: script.1515520944423
  alias: Update telefoon in broek
  condition:
  - condition: state
    entity_id: binary_sensor.zanzito_status_2
    state: 'on'
  id: automation_hurry_your_late
  trigger:
  - below: '5'
    entity_id: sensor.proximity_sensor
    platform: numeric_state
- id: '1543262156968'
  alias: Verzend mindergas.nl
  trigger:
  - at: '23:58:00'
    platform: time
  condition: []
  action:
  - service: rest_command.send_mindergas
