- id: '1543262156968'
  alias: Verzend mindergas.nl
  trigger:
  - at: '23:58:00'
    platform: time
  condition: []
  action:
  - service: rest_command.send_mindergas
- id: '1550605256142'
  alias: Update Yesterdays
  trigger:
  - hours: '23'
    minutes: '59'
    platform: time_pattern
    seconds: '30'
  condition: []
  action:
  - data:
      entity_id: 'sensor.yesterday_energy_consumption, sensor.yesterday_energy_netto,sensor.yesterday_energy_production,
        sensor.yesterday_growatt '
    service: homeassistant.update_entity
