homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude 
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 20
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret api_password 
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret base_url
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssh_key 

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

recorder:
  purge_interval: 2
  purge_keep_days: 5

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

upnp:
    port_mapping: false

# Text to speech
tts:
  - platform: google
    language: 'nl'

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Example configuration.yaml entry
media_player:
  - platform: spotify
    scan_interval: 10
    client_id: !secret spotify_client_id 
    client_secret: !secret spotify_client_secret
  - platform: kodi
    scan_interval: 3
    host: localhost
  - platform: snapcast
    host: localhost
  - platform: philips_js
    host: !secret philips_tv_ip
    api_version: 5

# Example configuration.yaml entry
notify:
  - platform: kodi
    name: NOTIFIER_NAME
    host: localhost

binary_sensor:
   - platform: workday
     country: NL

mqtt:
    broker: localhost
    port: 1885
    username: !secret username
    password: !secret mqtt_password
    keepalive: 3600
  
google_assistant:
    project_id: hass-io-skill
    client_id: !secret google_assistant_client_id 
    access_token: !secret google_assistant_access_token
    api_key: !secret google_assistant_api_key
    agent_user_id: !secret google_assistant_agent_user_id
    exposed_domains:
      - switch
      - light
      - group
      - media_player
      - scene

ifttt:
    key: !secret ifttt_key

rest_command:
    send_mindergas:
        url: https://www.mindergas.nl/api/gas_meter_readings
        method: POST
        headers: 
            AUTH-TOKEN: !secret minder_gas_auth_token
            Content-Type: application/json
        payload: '{"date" : "{{states.sensor.minder_gas_datum.state}}","reading" : {{ states.sensor.gas_consumption.state }}}'
        content_type:  'application/json'

# Get contents of subdirectories.
sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch