homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude 
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 20
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml


# Get contents of subdirectories.
!include_dir_merge_list components
sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch
media_player: !include_dir_merge_list media_player
rest_command: !include_dir_merge_list rest_command
binary_sensor: !include_dir_merge_list binary_sensor
notify: !include_dir_merge_list notify
tts: !include_dir_merge_list tts