# ----------------------------------------------------
# Instance
# ----------------------------------------------------
homeassistant:
    # Name of the location where Home Assistant is running
    name: Home
    # Location required to calculate the time the sun rises and sets
    latitude: !secret hass_latitude
    longitude: !secret hass_longitude 
    # Impacts weather/sunrise data (altitude above sea level in meters)
    elevation: 20
    # metric for Metric, imperial for Imperial
    unit_system: metric
    # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    time_zone: Europe/Amsterdam
    # Customization file
    customize: !include customize.yaml

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Cloud
cloud:

# ----------------------------------------------------
# UI
# ----------------------------------------------------

# Enables the frontend
frontend:

# Enables configuration UI
config:

# View all events in a logbook
logbook:

# Enables support for tracking state changes over time
history:

recorder:
    db_url: mysql://hass:2873nard@localhost/hass_db?charset=utf8

# Enables a map showing the location of tracked devices
map:

# Enable the device tracker
device_tracker:

# ----------------------------------------------------
# Glances
# ----------------------------------------------------
glances:

# ----------------------------------------------------
# History
# ----------------------------------------------------
history_graph:
  monthly_graphs:
    name: Monthly Graph
    entities:
      - sensor.monthly_gas
      - sensor.monthly_energy_netto_consumption
    hours_to_show: 744

# ----------------------------------------------------
# HTTP
# ----------------------------------------------------
http:
    # Secrets are defined in the file secrets.yaml
    # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
    base_url: !secret base_url
    ssl_certificate: !secret ssl_cert
    ssl_key: !secret ssh_key 

# ----------------------------------------------------
# Ecovacs
# ----------------------------------------------------
deebot:
  username: !secret ecovacs_username
  password: !secret ecovacs_password
  country: !secret ecovacs_countrycode
  continent: !secret ecovacs_continent

# ----------------------------------------------------
# Message brokers
# ----------------------------------------------------
mqtt:
    discovery: true
    broker: localhost
    port: 1885
    username: !secret username
    password: !secret mqtt_password
    keepalive: 3600

# ----------------------------------------------------
# Conversation/voice control
# ----------------------------------------------------

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

        #google_assistant
        #project_id: hass-io-skill
        #client_id: !secret google_assistant_client_id 
        #access_token: !secret google_assistant_access_token
        #api_key: !secret google_assistant_api_key
        #agent_user_id: !secret google_assistant_agent_user_id
        #exposed_domains:
        #- switch
        #- light
        #- group
        #- media_player
        #- scene

google_assistant:
    project_id: home-assistant-255919
    api_key: AIzaSyBqPr8j-HdQQYVuo0K6C2FB9TFWufJq2Go
# ----------------------------------------------------
# External automation
# ----------------------------------------------------

ifttt:
    key: !secret ifttt_key

# ----------------------------------------------------
# Google calendar integration
# ----------------------------------------------------

google:
    client_id: !secret google_calendar_id
    client_secret: !secret google_calendar_secret
    track_new_calendar: false

# ----------------------------------------------------
# Other components
# ----------------------------------------------------

# Track the sun
sun:

upnp:
    port_mapping: false

lovelace:
    resources:
    - url: /local/custom-lovelace/group-card/group-card.js?v=1
      type: js
    - url: /local/custom-lovelace/gauge-card/gauge-card.js?v=1
      type: js

# ----------------------------------------------------
# Configuration subdirectories/files
# ----------------------------------------------------
automation: !include automations.yaml
script: !include scripts.yaml
utility_meter: !include utility_meter.yaml

group: !include_dir_merge_named groups
sensor: !include_dir_merge_list sensor
climate: !include_dir_merge_list climate
timer: !include_dir_merge_named timer
input_number: !include_dir_merge_list input_number
switch: !include_dir_merge_list switch
media_player: !include_dir_merge_list media_player
rest_command: !include_dir_merge_named rest_command
binary_sensor: !include_dir_merge_list binary_sensor
notify: !include_dir_merge_list notify
tts: !include_dir_merge_list tts
