- platform: pulseaudio_loopback
  name: "Kodi on TV"
  sink_name: "tvaudio"
  source_name: "kodi_sink.monitor"
- platform: pulseaudio_loopback
  name: "Kodi on Radio"
  sink_name: "radioaudio"
  source_name: "kodi_sink.monitor"
- platform: pulseaudio_loopback
  name: "Kodi on Snapcast"
  sink_name: "snapcast"
  source_name: "kodi_sink.monitor"
- platform: pulseaudio_loopback
  name: "Spotify on TV"
  sink_name: "tvaudio"
  source_name: "spotify_sink.monitor"
- platform: pulseaudio_loopback
  name: "Spotify on Radio"
  sink_name: "radioaudio"
  source_name: "spotify_sink.monitor"
- platform: pulseaudio_loopback
  name: "Spotify on Snapcast"
  sink_name: "snapcast"
  source_name: "spotify_sink.monitor"
- platform: pulseaudio_loopback
  name: "Snapcast on TV"
  sink_name: "tvaudio"
  source_name: "snapcast_sink.monitor"
- platform: pulseaudio_loopback
  name: "Snapcast on Radio"
  sink_name: "radioaudio"
  source_name: "snapcast_sink.monitor"