- platform: mqtt
  name: Thermostat
  modes:
    - "auto"
    - "heat"
    - "off"
    
  mode_command_topic: "ems-esp/thermostat_cmd_mode1"
  temperature_command_topic: "ems-esp/thermostat_cmd_temp1"
   
  mode_state_topic: "ems-esp/thermostat_data"
  current_temperature_topic: "ems-esp/thermostat_data"
  temperature_state_topic: "ems-esp/thermostat_data"
  
  mode_state_template: "{% if value_json.hc1.mode in ['manual', 'day'] %} heat {% elif value_json.hc1.mode in ['night', 'off'] %} off {% else %} auto {% endif %}"

  current_temperature_template: "{{ value_json.hc1.currtemp }}"
  temperature_state_template: "{{ value_json.hc1.seltemp }}"
   
  temp_step: 0.5
  
- platform: mqtt
  name: Boiler
  modes:
    - "auto"
    - "off"
  min_temp: 40
  max_temp: 60
  temp_step: 1
  
  current_temperature_topic: "ems-esp/boiler_data"
  temperature_state_topic: "ems-esp/boiler_data"
  mode_state_topic: "ems-esp/boiler_data"

  current_temperature_template: "{{ value_json.wWCurTmp }}"
  temperature_state_template: "{{ value_json.wWSelTemp }}"
  mode_state_template: "{% if value_json.wWActivated == 'off' %} off {% else %} auto {% endif %}"

  temperature_command_topic: "ems-esp/boiler_cmd_wwtemp"
  mode_command_topic: "ems-esp/boiler_cmd_wwactivated"
  