- platform: template
  sensors:
    daily_solar_usage:
      friendly_name: "Solar usage daily"
      unit_of_measurement: 'kWh'
      value_template: "{{ ((states.sensor.daily_growatt.state | float ) -  ( states.sensor.daily_production_peak.state | float)) | float | round(3) }}"
