
# boiler
- platform: mqtt
  state_topic: 'ems-esp/boiler_data'
  name: 'Warm Water selected temperature'
  unit_of_measurement: '°C'
  value_template: '{{ value_json.wWSelTemp }}'

- platform: mqtt
  state_topic: 'ems-esp/boiler_data'
  name: 'Warm Water tapwater flow rate'
  unit_of_measurement: 'l/min'
  value_template: '{{ value_json.wWCurFlow }}'

- platform: mqtt
  state_topic: 'ems-esp/boiler_data'
  name: 'Warm Water current temperature'
  unit_of_measurement: '°C'
  value_template: '{{ value_json.wWCurTmp }}'

- platform: mqtt
  state_topic: 'ems-esp/boiler_data'
  name: 'Warm Water activated'
  value_template: '{{ value_json.wWActivated }}'

- platform: mqtt
  state_topic: 'ems-esp/boiler_data'
  name: 'Warm Water 3-way valve'
  value_template: '{{ value_json.wWHeat }}'

- platform: mqtt
  state_topic: 'ems-esp/boiler_data'
  name: 'Current flow temperature'
  unit_of_measurement: '°C'
  value_template: '{{ value_json.curFlowTemp }}'

- platform: mqtt
  state_topic: 'ems-esp/boiler_data'
  name: 'Return temperature'
  unit_of_measurement: '°C'
  value_template: '{{ value_json.retTemp }}'

- platform: mqtt
  state_topic: 'ems-esp/boiler_data'
  name: 'Gas'
  value_template: '{{ value_json.burnGas }}'

- platform: mqtt
  state_topic: 'ems-esp/boiler_data'
  name: 'Boiler pump'
  value_template: '{{ value_json.heatPmp }}'

- platform: mqtt
  state_topic: 'ems-esp/boiler_data'
  name: 'Fan'
  value_template: '{{ value_json.fanWork }}'

- platform: mqtt
  state_topic: 'ems-esp/boiler_data'
  name: 'Ignition'
  value_template: '{{ value_json.ignWork }}'

- platform: mqtt
  state_topic: 'ems-esp/boiler_data'
  name: 'Circulation pump'
  value_template: '{{ value_json.wWCirc }}'

- platform: mqtt
  state_topic: 'ems-esp/boiler_data'
  name: 'Burner max power'
  unit_of_measurement: '%'
  value_template: '{{ value_json.selBurnPow }}'

- platform: mqtt
  state_topic: 'ems-esp/boiler_data'
  name: 'Burner max power'
  unit_of_measurement: '%'
  value_template: '{{ value_json.selBurnPow }}'

- platform: mqtt
  state_topic: 'ems-esp/boiler_data'
  name: 'Burner current power'
  unit_of_measurement: '%'
  value_template: '{{ value_json.curBurnPow }}'

- platform: mqtt
  state_topic: 'ems-esp/boiler_data'
  name: 'System Pressure'
  unit_of_measurement: 'bar'
  value_template: '{{ value_json.sysPress }}'

- platform: mqtt
  state_topic: 'ems-esp/boiler_data'
  name: 'Boiler temperature'
  unit_of_measurement: '°C'
  value_template: '{{ value_json.boilTemp }}'

- platform: mqtt
  state_topic: 'ems-esp/boiler_data'
  name: 'Pump modulation'
  unit_of_measurement: '%'
  value_template: '{{ value_json.pumpMod }}'

# shower time duration
- platform: mqtt
  name: 'Last shower duration'
  state_topic: "ems-esp/shower_data"
  value_template: "{{ value_json.duration | is_defined }}"

- platform: template
  sensors:
    showertime_time:
      value_template: '{{ as_timestamp(states.sensor.last_shower_duration.last_updated) | int | timestamp_custom("%-I:%M on %a %-d %b") }}'
    boiler_updated:
      value_template: '{{ as_timestamp(states.sensor.boiler_temperature.last_updated) | timestamp_custom("%H:%M on %d/%b") }}'
    boiler_boottime:
      value_template: '{{ as_timestamp(states.automation.see_if_boiler_restarts.attributes.last_triggered) | timestamp_custom("%H:%M:%S %d/%m/%y") }}'

# general
- platform: mqtt
  state_topic: 'ems-esp/status'
  name: 'ems-esp status'

# example dallas sensor
- platform: mqtt
  state_topic: 'ems-esp/sensors'
  name: 'dallas sensor'
#  value_template: "{{ value_json['28FF47AC90160444'] }}"
  value_template: "{{ value_json.sensor1.temp }}"
  unit_of_measurement: '°C'
  
# EMS-ESP Statistics - heartbeat
- platform: mqtt
  state_topic: 'ems-esp/heartbeat'
  name: 'ems_esp_wifi'
  unit_of_measurement: '%'
  value_template: '{{ value_json.rssid }}'
  availability_topic: 'ems-esp/status'
  payload_available: "online"
  payload_not_available: "offline"

- platform: mqtt
  state_topic: 'ems-esp/heartbeat'
  name: 'ems_esp_load'
  unit_of_measurement: '%'
  value_template: '{{ value_json.load }}'
  availability_topic: 'ems-esp/status'
  payload_available: "online"
  payload_not_available: "offline"

- platform: mqtt
  state_topic: 'ems-esp/heartbeat'
  name: 'ems_esp_freemem'
  unit_of_measurement: '%'
  value_template: '{{ value_json.freemem }}'
  availability_topic: 'ems-esp/status'
  payload_available: "online"
  payload_not_available: "offline"

- platform: mqtt
  state_topic: 'ems-esp/heartbeat'
  name: 'ems_esp_uptime'
  unit_of_measurement: 's'
  value_template: '{{ value_json.uptime }}'
  availability_topic: 'ems-esp/status'
  payload_available: "online"
  payload_not_available: "offline"

- platform: mqtt
  state_topic: 'ems-esp/heartbeat'
  name: 'ems_esp_tcpdrops'
  value_template: '{{ value_json.tcpdrops }}'
  availability_topic: 'ems-esp/status'
  payload_available: "online"
  payload_not_available: "offline"

- platform: mqtt
  state_topic: 'ems-esp/heartbeat'
  name: 'ems_esp_mqttpublishfails'
  value_template: '{{ value_json.mqttpublishfails }}'
  availability_topic: 'ems-esp/status'
  payload_available: "online"
  payload_not_available: "offline"