- platform: template
  sensors:
    energieverbruik:
      value_template: '{{ ((states.sensor.growatt_total_output_power.state | float ) - (states.sensor.power_production.state | float)) | round(3)}}'
      friendly_name: Usage of solarenergy
      unit_of_measurement: kW
