- platform: template
  sensors:
    energieverbruik:
      value_template: '{{(states.sensor.growatt.state | float ) - (states.sensor.power_production.state | float)}}'
      friendly_name: Usage of solarenergy
      unit_of_measurement: kW
