- platform: template
  sensors:
    consumption_total:
      friendly_name: "P1 Consumption Total"
      value_template: "{{ (( states('sensor.p1_consumption_low_tarif') | float + states('sensor.p1_consumption_high_tarif') | float )) | round(3) }}"
      unit_of_measurement: 'kWh'
- platform: template
  sensors:
    delivery_total:
      friendly_name: "P1 Delivery Total"
      value_template: "{{ (( states('sensor.p1_delivery_low_tarif') | float + states('sensor.p1_delivery_high_tarif') | float )) | round(3) }}"
      unit_of_measurement: 'kWh'
- platform: template
  sensors:
    daily_netto_total:
      friendly_name: "Netto consumption daily"
      unit_of_measurement: 'kWh'
      value_template: "{{ (( states('sensor.daily_consumption') | float + states('sensor.daily_delivery') | float )) | round(3) }}"
- platform: template
  sensors:
    monthly_netto_total:
      friendly_name: "Netto consumption Monthly"
      unit_of_measurement: 'kWh'
      value_template: "{{ (( states('sensor.monthly_consumption') | float - states('sensor.monthly_delivery') | float )) | round(3) }}"
- platform: template
  sensors:
    yearly_netto_total:
      friendly_name: "Netto consumption Yearly"
      unit_of_measurement: 'kWh'
      value_template: "{{ (( states('sensor.yearly_consumption') | float - states('sensor.yearly_delivery') | float )) | round(3) }}"
- platform: template
  sensors:
    actual_energy:
      friendly_name: "Actual used or delivered energy"
      unit_of_measurement: 'kWh'
      value_template: "{{ (( states('sensor.p1_actual_power_consumption') | float - states('sensor.p1_actual_power_delivery') | float )) | round(3) }}"
