- platform: template
   sensors:
      consumption_total:
        friendly_name: "P1 Consumption Total"
        value_template: "{{ states('sensor.consumption_low_tarif') | float + states('sensor.consumption_high_tarif') | float }}"
        unit_of_measurement: 'kWh'
- platform: template
   sensors:
      delivery_total:
        friendly_name: "P1 Delivery Total"
        value_template: "{{ states('sensor.p1_delivery_low_tarif') | float + states('sensor.p1_delivery_high_tarif') | float }}"
        unit_of_measurement: 'kWh'
- platform: template
  sensors:
    energy_netto_consumption:
      friendly_name: "Netto consumption daily"
      unit_of_measurement: 'kWh'
      value_template: "{{ ((states.sensor.daily_consumption_peak.state | float) - (states.sensor.daily_production_peak.state | float )) | round(3) }}"
- platform: template
  sensors:
    monthly_energy_netto_consumption:
      friendly_name: "Netto consumption monthly"
      unit_of_measurement: 'kWh'
      value_template: "{{ ((states.sensor.monthly_consumption_peak.state | float) - (states.sensor.monthly_production_peak.state | float )) | round(3) }}"
