- platform: template
  sensors:
    energy_production_total:
      friendly_name: "Production Total"
      unit_of_measurement: 'kWh'
      value_template: "{{ ((states.sensor.power_production_low.state | float) + (states.sensor.power_production_normal.state | float)) | round(3) }}"
- platform: template
  sensors:
    energy_consumption_total:
      friendly_name: "Consumption Total"
      unit_of_measurement: 'kWh'
      value_template: "{{ ((states.sensor.power_consumption_low.state | float) + (states.sensor.power_consumption_normal.state | float)) | round(3) }}"
- platform: template
  sensors:
    energy_netto_consumption:
      friendly_name: "Netto consumption daily"
      unit_of_measurement: 'kWh'
      value_template: "{{ ((states.sensor.daily_consumption_peak.state | float) - (states.sensor.daily_production_peak.state | float )) | round(3) }}"
- platform: template
  sensors:
    energy_netto_consumption:
      friendly_name: "Netto consumption monthly"
      unit_of_measurement: 'kWh'
      value_template: "{{ ((states.sensor.monthly_consumption_peak.state | float) - (states.sensor.monthly_production_peak.state | float )) | round(3) }}"
