- platform: growatt
  username: !secret growatt_username
  password: !secret growatt_password
- platform: template
  sensors:
    energy_generation:
      value_template: '{% if is_state_attr("sensor.growatt", "power_generation", "NaN") %}0{% else %}{{ "%0.2f"|format(states.sensor.growatt.attributes.power_generation|float) }}{% endif %}'
      friendly_name: 'Generated'
      unit_of_measurement: 'kWh'
