- platform: template
  sensors:
      minder_gas_datum:
          entity_id: sensor.time__date
          friendly_name: "Datum minder gas"
          value_template: "{{ as_timestamp(now()) | timestamp_custom('%Y-%m-%d', True) }}"
