- platform: template
  sensors:
    solar_energy_from_sun:
      friendly_name: "Energy From Sun"
      unit_of_measurement: 'kWh'
      value_template: "{{ (( 1.6236*9 | float) * ( states.sensor.br_irradiance_2.state | float ) / 1000) | round(3) }}"
- platform: template
  sensors:
    solar_efficiency:
      friendly_name: "Solar Efficiency"
      unit_of_measurement: '%'
      value_template: "{{ ((100 * states. sensor.growatt.state | float) / states.sensor.solar_energy_from_sun.state | float) | round(2) }}"
