- platform: template
  sensors:
      phone_wifi_ssid:
          friendly_name: "Wifi SSID"
          value_template: "{{ state_attr('sensor.lenovo_p2_wifi_sensor', 'ssid') }}"

- platform: template
  sensors:
      phone_wifi_rssi1:
          friendly_name: "Wifi RSSI"
          unit_of_measurement: dBm
          value_template: "{{ state_attr('sensor.lenovo_p2_wifi_sensor', 'rssi')|int  }}"
